### ISSUE TITLE
permissions/update orror

### ISSUE THREAD

**Issue by Khludev** [wikichua/simplecontrolpanel#1]
There was already such a mistake. But I don’t remember how I єє decided
"Facade\Ignition\Exceptions\ViewException
Invalid argument supplied for foreach() (View: /var/www/sitename/resources/views/vendor/lap/permissions/update.blade.php) "

**Comment by Khludev** [comment]
> There was already such a mistake. But I don’t remember how I єє decided
> "Facade\Ignition\Exceptions\ViewException
> Invalid argument supplied for foreach() (View: /var/www/sitename/resources/views/vendor/lap/permissions/update.blade.php) "

I now realized that you need to install the panel from the "Wiki" tab

**Comment by wikichua** [comment]
@Khludev that could be my mistake. 
![image](https://user-images.githubusercontent.com/1870466/66794034-86c56f00-ef32-11e9-9ba3-4e8aebf294f2.png)
I suspecting the loop cause by this. would you check if your lap.php in your config contains this?
