### ISSUE TITLE
Translations for Admin modules

### ISSUE THREAD

**Issue by Khludev** [wikichua/simplecontrolpanel#10]
![Выделение_016](https://user-images.githubusercontent.com/47009408/69793503-3dbf3680-11d1-11ea-875f-83d3aa31b432.png)
I have a new project requiring a complete translation of the admin panel.
As you propose to do:
1. Make transfers by type of stubs.
2. To do vendor:publish a view folder.
3.  Or your suggestions))

**Comment by Khludev** [comment]
> I have a new project requiring a complete translation of the admin panel.
> As you propose to do:
> 
>     1. Make transfers by type of stubs.
> 
>     2. To do vendor:publish a view folder.
> 
>     3. Or your suggestions))

**Comment by Khludev** [comment]
> ![Выделение_016](https://user-images.githubusercontent.com/47009408/69793503-3dbf3680-11d1-11ea-875f-83d3aa31b432.png)
> I have a new project requiring a complete translation of the admin panel.
> As you propose to do:
> 
>     1. Make transfers by type of stubs.
> 
>     2. To do vendor:publish a view folder.
> 
>     3. Or your suggestions))

**Comment by wikichua** [comment]
@Khludev thanks. appreciated ur commitment. cheers
