### ISSUE TITLE
Lang

### ISSUE THREAD

**Issue by Khludev** [wikichua/simplecontrolpanel#11]
https://github.com/wikichua/simplecontrolpanel/issues/10

**Comment by wikichua** [comment]
![image](https://user-images.githubusercontent.com/1870466/69838357-2bef9900-128e-11ea-9f27-b89c47e4405d.png)

perhaps this could be better deal?

segregated each, so we have ability to decide which to transfer.

**Comment by wikichua** [comment]
![image](https://user-images.githubusercontent.com/1870466/69839212-92c28180-1291-11ea-8b77-581ad66cfaa2.png)
