### ISSUE TITLE
Publish Stubs no in Description

### ISSUE THREAD

**Issue by Khludev** [wikichua/simplecontrolpanel#13]
php artisan vendor:publish --tag=lap.stubs

**Comment by wikichua** [comment]
shyte. u found out. was trying to hide that. lol. anyway. i updated it.

**Comment by wikichua** [comment]
u would probably wan to pull my latest. as i added auto generate filter inputs. not all supported for now. at least, the necessary 1

**Comment by Khludev** [comment]
> u would probably wan to pull my latest. as i added auto generate filter inputs. not all supported for now. at least, the necessary 1

I already pulled out and testing))
