### ISSUE TITLE
Error Foundation\Application::find ()

### ISSUE THREAD

**Issue by Khludev** [wikichua/simplecontrolpanel#16]
Hello Wikichua.

I noticed an error while updating Seotools for recording.
(Call to undefined method Illuminate \ Foundation \ Application :: find ()).

![Выделение_064](https://user-images.githubusercontent.com/47009408/71322569-98e30100-24d1-11ea-9612-bd55033f74ce.png)

**Comment by wikichua** [comment]
Noted. will take a look on this.

**Comment by wikichua** [comment]
I cant remember if i fix it. but i cant replicate this error. let me know if u r still facing this. thnks
