### ISSUE TITLE
trait DynamicFillable

### ISSUE THREAD

**Issue by Khludev** [wikichua/simplecontrolpanel#17]
Found. Another nuance in the trait "DynamicFillable".
When trait is connected, it significantly increases the number of database calls to get column names, even if they are not needed.
For a small project, this is not critical. But in another case, it is even very important.
Until I began to research this issue, since I do not need it yet

**Comment by wikichua** [comment]
Sorry that I will be away for few months due to settling something important. will get be on this soonest possible

**Comment by wikichua** [comment]
![image](https://user-images.githubusercontent.com/1870466/82121731-d36f7200-97c1-11ea-8bd1-93b71bcd9c4e.png)
