### ISSUE TITLE
Documentation for CRUD

### ISSUE THREAD

**Issue by asimshazad** [wikichua/simplecontrolpanel#2]
Thank you for extending this awesome packages. I really appreciate your time and effort. Currently, I can't see any documentation on how to use a crud generator. Can you please let me know how can I use it.

Thank you

**Comment by Khludev** [comment]
> Thank you for extending this awesome packages. I really appreciate your time and effort. Currently, I can't see any documentation on how to use a crud generator. Can you please let me know how can I use it.
> 
> Thank you


If urgently needed, you can use this
artisan crud:config NameNewModel -> generate config file
artisan crud:generate NameNewModel -> generate crud files
artisan crud:generate NameNewModel  --force regenerate all crud files flag

**Comment by Khludev** [comment]
It would be nice to name the configuration files for example either "news_crud.php" or simply "news.php" instead of News.php. Since I confuse with the model.
Although maybe it's just not convenient just for me)

**Comment by wikichua** [comment]
@Khludev i din do much changes from the original creator. as i found its ok to just use the model name in config/crud directory. however, great idea/suggestion will always be listed in my todo.

**Comment by asimshazad** [comment]
Thank you @Khludev & @wikichua.It is working perfectly.

**Comment by Khludev** [comment]
> It would be nice to name the configuration files for example either "news_crud.php" or simply "news.php" instead of News.php. Since I confuse with the model.
> Although maybe it's just not convenient just for me)

It only dawned on me that "settings" can simply be replaced with "config" and we will get a config file
```
                'options' => [
                    'config:backend.status_publication' => [
                        'key' => 'val',
                    ]],
```

"config:backend.status_publication" analog config('backend.status_publication').
