### ISSUE TITLE
Error on reset password "Route [password.reset] not defined."

### ISSUE THREAD

**Issue by Khirad2013** [wikichua/simplecontrolpanel#21]
Hi @wikichua 
Thank you for this awesome package. I am using this package for couple of my projects and today I noted an issue with reset password "Route [password.reset] not defined." Can you please have a look at this.

Thank you.

**Comment by wikichua** [comment]
Thank q. Sorry that I'm outstation for couple months. I'll be working on it
when i have chance to regain my access. Hope i wont hold back you progress.

**Comment by wikichua** [comment]
@Khirad2013 

sorry for the delay, I had update the code. pls let me know if its does not solve ur issue.

thanks
