### ISSUE TITLE
Upgrade to Laravel 7

### ISSUE THREAD

**Issue by asimshazad** [wikichua/simplecontrolpanel#22]
Thank you for such a nice package, I am using it in a couple of my projects and really amazed how nice it is.
Are you planning it to upgrade it to Laravel 7 besides some bugs fixes?

Thank you.

**Comment by wikichua** [comment]
Hi yes i will, as currently im facing some issue on my side, for now the maintenance might be on hold. I will upgrade this to support L7 asap.

**Comment by wikichua** [comment]
@asimshazad 
sorry for the delay, i have done some update. basically to support laravel 7 for now, u need to run composer require laravel/ui 
latest version
pls do let me know if there is any unsupported in Larave 7 as I don have any much project to test with using L7.

thanks

**Comment by wikichua** [comment]
pls do close the issue if fix.

thanks

**Comment by asimshazad** [comment]
I will test it and let you know.
Thank you
