### ISSUE TITLE
Duplicate admin routes

### ISSUE THREAD

**Issue by asimshazad** [wikichua/simplecontrolpanel#23]
Inside web.php admin routes keep adding thought it does not create any issue but better to fix it.

<img width="324" alt="Code_4K20S2NwXb" src="https://user-images.githubusercontent.com/14991207/81473349-3dfb3d80-9217-11ea-8e03-1560e3d62db5.png">

**Comment by wikichua** [comment]
did u  publishing the 2nd times?

**Comment by wikichua** [comment]
php artisan vendor:publish --tag=lap.admin.route --force // this will be republish the routes.php into admin directory also append the include_once(resource_path('../routes/admin/routes.php'));
however i would still like to replicate how u successfully got this. as i tried multiple even force publish not getting this

**Comment by wikichua** [comment]
![errortest](https://user-images.githubusercontent.com/1870466/81527190-39a46100-938c-11ea-84fd-67bd31ad4787.gif)

**Comment by wikichua** [comment]
![errortest](https://user-images.githubusercontent.com/1870466/81527403-bc2d2080-938c-11ea-928e-ea00f15f598a.gif)

**Comment by wikichua** [comment]
let me know if this issue can close

**Comment by asimshazad** [comment]
Ok, I will check it again.
