### ISSUE TITLE
crud.config.input.option from configuration file

### ISSUE THREAD

**Issue by Khludev** [wikichua/simplecontrolpanel#3]
The task was to output data from the config file “config / backend.php” because the expression (
`@foreach (['NOT_PUBLISHED', 'PUBLISHED', 'DRAFT'] as $ option)`
) is not entirely correct in my case.
Is it possible to write “config ('backend.status_publication')” in the config file of crud?

**Comment by wikichua** [comment]
my suggestion is using settings('status_publication')
as in the panel, there is a system settings, where you can add array in it. but pls do AWARE, its only for single level of array. 

![image](https://user-images.githubusercontent.com/1870466/66793927-11f23500-ef32-11e9-9d31-443d5f6364ed.png)

**Comment by wikichua** [comment]
@Khludev 
alternative you may follow as per image. 
create your backend.php in config. then change the settings to config:status_publication
it should be working as well
![image](https://user-images.githubusercontent.com/1870466/66892220-b9986180-f01d-11e9-99b2-dcd0cb230ff8.png)

**Comment by Khludev** [comment]
> @Khludev
> alternative you may follow as per image.
> create your backend.php in config. then change the settings to config:status_publication
> it should be working as well
> ![image](https://user-images.githubusercontent.com/1870466/66892220-b9986180-f01d-11e9-99b2-dcd0cb230ff8.png)

In my case, I need “config ('backend.status_publication')” instead of “settings ('backend.status_publication')”
Since settings ('backend.status_publication') is data from the database. And config ('backend.status_publication') is the data from the config file
