### ISSUE TITLE
widgets help

### ISSUE THREAD

**Issue by Khludev** [wikichua/simplecontrolpanel#9]
Hello Wiki Chua
Tell me how to work with widgets..

**Comment by wikichua** [comment]
sorry was busy these days. will get back to u very soon. sorry about this

**Comment by wikichua** [comment]
@Khludev 
btw, was thinking about the translation u added in. does it really making sense?
i was half way working on this actually. lol.. but i saw the objective of ur making. to try to generate the pre translated wordings into the stubs. i was thinking to make it more generalize so the localization could be done on demand. what do u think?

**Comment by wikichua** [comment]
btw, was thinking about the translation u added in. does it really making sense?
i was half way working on this actually. lol.. but i saw the objective of ur making. to try to generate the pre translated wordings into the stubs. i was thinking to make it more generalize so the localization could be done on demand. what do u think? @Khludev

**Comment by wikichua** [comment]
![image](https://user-images.githubusercontent.com/1870466/69697536-afd64380-111d-11ea-84f4-dfaecce41af1.png)
@ @Khludev 
sorry bout this. but wondering if u have this problem?

**Comment by Khludev** [comment]
Hello.
Everything works fine for me

**Comment by Khludev** [comment]
> ![image](https://user-images.githubusercontent.com/1870466/69697536-afd64380-111d-11ea-84f4-dfaecce41af1.png)
> @ @Khludev
> sorry bout this. but wondering if u have this problem?

Hello.
Everything works fine for me

**Comment by Khludev** [comment]
![Выделение_014](https://user-images.githubusercontent.com/47009408/69704801-dfc11f00-10fc-11ea-8536-5b06158d875e.png)
> btw, was thinking about the translation u added in. does it really making sense?
> i was half way working on this actually. lol.. but i saw the objective of ur making. to try to generate the pre translated wordings into the stubs. i was thinking to make it more generalize so the localization could be done on demand. what do u think? @Khludev

I also thought about localization on demand.
But I already did 3 projects and for each I had to do translations.
At first, I had the idea of ​​creating separate stubs templates in the folder (/resources/stubs/crud/default_trats..)/ But in the future, when changing the stubs of a file in the / crud / default folder, also change it in the / crud / default_trans folder, which time consuming.

If localization is not required, you do not need to copy the translation folder. It is only necessary to pass the __l ($ key, $ default_text) function as the second parameter to the default text.

**Comment by Khludev** [comment]
> > btw, was thinking about the translation u added in. does it really making sense?
> > i was half way working on this actually. lol.. but i saw the objective of ur making. to try to generate the pre translated wordings into the stubs. i was thinking to make it more generalize so the localization could be done on demand. what do u think? @Khludev
> 
> I also thought about localization on demand.
> But I already did 3 projects and for each I had to do translations.
> At first, I had the idea of ​​creating separate stubs templates in the folder (/resources/stubs/crud/default_trats..)/ But in the future, when changing the stubs of a file in the / crud / default folder, also change it in the / crud / default_trans folder, which time consuming.
> 
> If localization is not required, you do not need to copy the translation folder. It is only necessary to pass the __l ($ key, $ default_text) function as the second parameter to the default text.

![Выделение_014](https://user-images.githubusercontent.com/47009408/69704778-d33cc680-10fc-11ea-996f-f1128a6cb171.png)

**Comment by Khludev** [comment]
@wikichua  What are your ideas for translations?

**Comment by wikichua** [comment]
i think ur solution should be works fine. just bit of tweak to allow change lang on demand. let figure out. as the widget. simply crud:widget. this will create a widget class in the app directory and also the widget  blade according to ur config. crud:widget Tag for example. however there is no charts implemented as i thought this could be various and depend on developer. simplest is just throw in the table. to call and use it. simply @widget(ClassName). note there is not single or double quote in ClassName. so i just leave as it is.

**Comment by Khludev** [comment]
Thanks. @Widget(Menu) worked.
I recently switched to Laravel from Codeigniter.
Therefore, I do not know all the nuances so far.

**Comment by wikichua** [comment]
@Khludev no worries. appreciated ur participate. we learn together. 
actually there is alternative way, u will realize i don use npm in this project. in fact. most advise to use it so ur client scripts can be minified and much easier to manage, its like composer. but then, its fine, since this is admin panel.
